#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App7.Resource", IsApplication=true)]

namespace App7
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int banner = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000c
			public const int btn_ResultConfirm = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int btn_add_player = 2131034128;
			
			// aapt resource value: 0x7f050002
			public const int btn_add_player_photo = 2131034114;
			
			// aapt resource value: 0x7f050014
			public const int btn_exit = 2131034132;
			
			// aapt resource value: 0x7f050027
			public const int btn_go_to_game = 2131034151;
			
			// aapt resource value: 0x7f050016
			public const int btn_list_player_done = 2131034134;
			
			// aapt resource value: 0x7f050006
			public const int btn_new_player_cancel = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int btn_new_player_done = 2131034117;
			
			// aapt resource value: 0x7f050012
			public const int btn_play_game = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int btn_start_league = 2131034131;
			
			// aapt resource value: 0x7f05000d
			public const int btn_table_goHome = 2131034125;
			
			// aapt resource value: 0x7f050026
			public const int btn_view_player_done = 2131034150;
			
			// aapt resource value: 0x7f050011
			public const int btn_view_players = 2131034129;
			
			// aapt resource value: 0x7f05000b
			public const int edit_AwayScore = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int edit_HomeScore = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int edit_new_player_ID = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int edit_new_player_name = 2131034115;
			
			// aapt resource value: 0x7f05000f
			public const int img_banner = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int img_new_player_photo = 2131034113;
			
			// aapt resource value: 0x7f05001e
			public const int img_view_player = 2131034142;
			
			// aapt resource value: 0x7f050017
			public const int list_player_list = 2131034135;
			
			// aapt resource value: 0x7f05002b
			public const int list_select_game_players = 2131034155;
			
			// aapt resource value: 0x7f05000e
			public const int list_table = 2131034126;
			
			// aapt resource value: 0x7f050028
			public const int radioGroup1 = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int radio_one_leg = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int radio_two_leg = 2131034154;
			
			// aapt resource value: 0x7f050021
			public const int rating_view_player_score = 2131034145;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050015
			public const int textView2 = 2131034133;
			
			// aapt resource value: 0x7f05001a
			public const int txtDraw = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int txtGA = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int txtLose = 2131034139;
			
			// aapt resource value: 0x7f050018
			public const int txtName = 2131034136;
			
			// aapt resource value: 0x7f05001d
			public const int txtPoint = 2131034141;
			
			// aapt resource value: 0x7f050019
			public const int txtWin = 2131034137;
			
			// aapt resource value: 0x7f05000a
			public const int txt_AwayName = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int txt_Fixture = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int txt_HomeName = 2131034120;
			
			// aapt resource value: 0x7f050022
			public const int txt_view_player_games = 2131034146;
			
			// aapt resource value: 0x7f050024
			public const int txt_view_player_goal = 2131034148;
			
			// aapt resource value: 0x7f050020
			public const int txt_view_player_id = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int txt_view_player_name = 2131034143;
			
			// aapt resource value: 0x7f050023
			public const int txt_view_player_point = 2131034147;
			
			// aapt resource value: 0x7f050025
			public const int txt_view_player_stat = 2131034149;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddPlayerLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GamesAndTable = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HomeBannerLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HomePageLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListOfPlayersLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MyCustomListView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PlayerStatLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PlayGamePlayers = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
